import { FormEvent, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { ArrowRight, CheckCircle2, ChevronDown, ChevronUp, CircleAlert, Minus, Package, Plus, Search, ShoppingBag, Trash2, UserRound } from 'lucide-react';
import { api, getCurrentUser } from '@/lib/api';
import { PageHeader, formatMoney } from '@/components/page-header';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';
import { cn } from '@/lib/utils';
import { useBackendNotifications } from '@/components/notification-center';
import { useCart } from '@/lib/cart';
import { OrderDetailSkeleton, TableSkeleton } from '@/components/ui/skeleton';

type Product = { id: string; name: string; sku: string; image: string | null; salePrice: string; currentStock: string; active: boolean; category: { name: string } };
type Order = { id: string; status: string; totalAmount: number; createdAt: string; items: { product?: { name: string }; quantity?: number }[] };

function statusVariant(status: string): 'default' | 'success' | 'warning' | 'destructive' | 'outline' {
  if (status === 'COMPLETED') return 'success';
  if (status === 'REJECTED' || status === 'CANCELLED') return 'destructive';
  if (status === 'PENDING') return 'warning';
  return 'default';
}
function statusLabel(status: string) { return ({ PENDING: 'En attente', ACCEPTED: 'Acceptée', PREPARING: 'En préparation', READY: 'Prête', COMPLETED: 'Terminée', REJECTED: 'Refusée', CANCELLED: 'Annulée' } as Record<string, string>)[status] ?? status; }

export function ClientDashboardPage() {
  const { data: orders = [], isLoading } = useQuery({ queryKey: ['client-orders'], queryFn: () => api<Order[]>('/client/orders') });
  const { data: notifications = [] } = useBackendNotifications();
  const activeOrders = orders.filter((order) => !['COMPLETED', 'REJECTED', 'CANCELLED'].includes(order.status));
  return <div className="space-y-7">
    <section className="relative overflow-hidden rounded-2xl bg-sidebar px-6 py-7 text-sidebar-foreground shadow-lg sm:px-8">
      <div className="relative z-10 max-w-xl"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-primary">Espace client</p><h1 className="text-3xl font-semibold tracking-tight">Bonjour{getCurrentUser()?.name ? `, ${getCurrentUser()?.name}` : ''}</h1><p className="mt-2 text-sm leading-6 text-sidebar-muted">Retrouvez vos commandes, découvrez le catalogue et suivez chaque étape de vos achats.</p><Link to="/client/products" className="mt-5 inline-flex"><Button><ShoppingBag className="h-4 w-4" />Parcourir le catalogue<ArrowRight className="h-4 w-4" /></Button></Link></div>
      <div className="absolute -right-8 -top-16 h-56 w-56 rounded-full border-[28px] border-primary/20" />
      <div className="absolute -bottom-24 right-24 h-48 w-48 rounded-full border-[18px] border-white/10" />
    </section>
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Toutes mes commandes" value={String(orders.length)} icon={Package} /><Metric label="En cours" value={String(activeOrders.length)} icon={CircleAlert} /><Metric label="Notifications" value={String(notifications.filter((item) => !item.readAt).length)} icon={CheckCircle2} /></div>
    <div className="grid gap-6 xl:grid-cols-[1.45fr_1fr]">
      <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Commandes récentes</h2><p className="text-sm text-muted-foreground">Vos dernières activités</p></div><Link to="/client/orders" className="text-sm font-semibold text-primary">Tout voir</Link></div>{isLoading ? <p className="py-8 text-sm text-muted-foreground">Chargement…</p> : orders.length === 0 ? <EmptyState icon={ShoppingBag} title="Aucune commande" text="Votre prochaine commande apparaîtra ici." action={<Link to="/client/products"><Button size="sm">Découvrir les produits</Button></Link>} /> : <div className="divide-y divide-border/70">{orders.slice(0, 5).map((order) => <OrderRow key={order.id} order={order} />)}</div>}</section>
      <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">À ne pas manquer</h2><p className="text-sm text-muted-foreground">Vos dernières notifications</p></div><Link to="/client/notifications" className="text-sm font-semibold text-primary">Voir tout</Link></div>{notifications.slice(0, 3).map((item) => <div key={item.id} className={cn('border-b border-border/70 py-3 text-sm last:border-0', !item.readAt && 'font-semibold')}><p>{item.title}</p><p className="mt-1 text-xs font-normal text-muted-foreground">{item.message}</p></div>)}{!notifications.length ? <p className="py-8 text-center text-sm text-muted-foreground">Aucune notification pour le moment.</p> : null}</section>
    </div>
  </div>;
}

export function ClientProductsPage() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('Toutes'); const [quantities, setQuantities] = useState<Record<string, number>>({});
  const { addItem } = useCart();
  const { data, isLoading } = useQuery({ queryKey: ['client-products', query], queryFn: () => api<{ items: Product[]; total: number }>(`/products?active=true&q=${encodeURIComponent(query)}`) });
  const products = (data?.items ?? []).filter((product) => category === 'Toutes' || product.category?.name === category);
  const categories = ['Toutes', ...Array.from(new Set((data?.items ?? []).map((product) => product.category?.name).filter(Boolean)))];
  function setQuantity(id: string, value: number) { setQuantities((current) => ({ ...current, [id]: Math.max(1, value) })); }
  function add(product: Product) { addItem(product, quantities[product.id] ?? 1); toast.success(`${product.name} ajouté au panier`); }
  return <div className="space-y-6"><PageHeader title="Catalogue" subtitle="Des produits disponibles pour votre activité." actions={<Link to="/client/cart"><Button variant="outline"><ShoppingBag className="h-4 w-4" />Panier</Button></Link>} /><div className="flex flex-col gap-3 rounded-2xl border bg-card p-4 shadow-sm md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un produit ou une référence" /></div><div className="flex gap-2 overflow-x-auto">{categories.map((item) => <Button key={item} size="sm" variant={category === item ? 'default' : 'outline'} onClick={() => setCategory(item)}>{item}</Button>)}</div></div>{isLoading ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3"><LoadingCard /><LoadingCard /><LoadingCard /></div> : !products.length ? <EmptyState icon={Search} title="Aucun produit trouvé" text="Modifiez votre recherche ou choisissez une autre catégorie." /> : <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{products.map((product) => <ProductCard key={product.id} product={product} quantity={quantities[product.id] ?? 1} onQuantity={(value) => setQuantity(product.id, value)} onAdd={() => add(product)} />)}</div>}</div>;
}

function ProductCard({ product, quantity, onQuantity, onAdd }: { product: Product; quantity: number; onQuantity: (value: number) => void; onAdd: () => void }) {
  const available = Number(product.currentStock) > 0 && product.active;
  return <Card className="overflow-hidden transition-shadow hover:shadow-lg"><Link to={`/client/products/${product.id}`} className="block">{product.image ? <img src={product.image} alt={product.name} className="h-48 w-full object-cover" /> : <div className="flex h-48 items-center justify-center bg-muted text-muted-foreground"><Package className="h-10 w-10" /></div>}</Link><CardContent className="space-y-4 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{product.category?.name}</p><h3 className="mt-1 font-semibold">{product.name}</h3><p className="mt-1 text-xs text-muted-foreground">Réf. {product.sku}</p></div><Badge variant={available ? 'success' : 'destructive'}>{available ? 'Disponible' : 'Rupture'}</Badge></div><div className="flex items-end justify-between"><span className="text-xl font-semibold">{Number(product.salePrice).toFixed(3)} DT</span><span className="text-xs text-muted-foreground">{Number(product.currentStock)} en stock</span></div><div className="flex gap-2"><div className="flex h-10 items-center rounded-lg border"><Button type="button" size="icon" variant="ghost" onClick={() => onQuantity(quantity - 1)}><Minus className="h-3.5 w-3.5" /></Button><span className="w-7 text-center text-sm font-semibold">{quantity}</span><Button type="button" size="icon" variant="ghost" onClick={() => onQuantity(quantity + 1)}><Plus className="h-3.5 w-3.5" /></Button></div><Button className="flex-1" disabled={!available} onClick={onAdd}>Ajouter au panier</Button></div></CardContent></Card>;
}

export function ClientProductDetailPage() {
  const { id } = useParams(); const { data, isLoading } = useQuery({ queryKey: ['client-product', id], queryFn: () => api<Product>(`/products/${id}`) });
  const { addItem } = useCart();
  if (isLoading || !data) return <p className="text-sm text-muted-foreground">Chargement du produit…</p>;
  const available = Number(data.currentStock) > 0 && data.active;
  return <div className="space-y-6"><PageHeader title={data.name} subtitle={`Référence ${data.sku}`} /><div className="grid gap-8 rounded-2xl border bg-card p-5 shadow-sm lg:grid-cols-[1.1fr_1fr] lg:p-8"><div>{data.image ? <img src={data.image} alt={data.name} className="aspect-[4/3] w-full rounded-xl object-cover" /> : <div className="flex aspect-[4/3] items-center justify-center rounded-xl bg-muted"><Package className="h-16 w-16 text-muted-foreground/50" /></div>}</div><div className="flex flex-col justify-center"><Badge variant={available ? 'success' : 'destructive'} className="w-fit">{available ? 'Disponible' : 'Rupture de stock'}</Badge><p className="mt-5 text-4xl font-semibold">{Number(data.salePrice).toFixed(3)} DT</p><p className="mt-2 text-sm text-muted-foreground">Catégorie: {data.category?.name} · {Number(data.currentStock)} unité(s) disponible(s)</p><Button className="mt-7 w-full sm:w-fit" disabled={!available} onClick={() => { addItem(data); toast.success('Produit ajouté au panier'); }}>Ajouter au panier</Button></div></div></div>;
}

export function ClientCartPage() {
  const { cart, totalPrice, updateQuantity } = useCart(); const entries = Object.values(cart);
  return <div className="space-y-6"><PageHeader title="Votre panier" subtitle={`${entries.length} référence(s) sélectionnée(s).`} /><div key={totalPrice} className="grid gap-6 lg:grid-cols-[1fr_350px]">{!entries.length ? <section className="rounded-2xl border bg-card p-12 text-center shadow-sm"><ShoppingBag className="mx-auto mb-4 h-12 w-12 text-muted-foreground/40" /><h2 className="font-semibold">Votre panier est vide</h2><p className="mt-1 text-sm text-muted-foreground">Ajoutez des produits pour préparer votre commande.</p><Link to="/client/products" className="mt-5 inline-flex"><Button>Voir le catalogue</Button></Link></section> : <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="divide-y divide-border/70">{entries.map((item) => <div key={item.productId} className="flex gap-4 py-4 first:pt-0"><div className="hidden h-16 w-16 shrink-0 items-center justify-center rounded-lg bg-muted sm:flex">{item.image ? <img src={item.image} alt="" className="h-full w-full rounded-lg object-cover" /> : <Package className="h-6 w-6 text-muted-foreground" />}</div><div className="min-w-0 flex-1"><p className="font-semibold">{item.productName}</p><p className="mt-1 text-sm text-muted-foreground">{item.unitPrice.toFixed(3)} DT / unité</p><div className="mt-3 flex items-center gap-2"><Button size="icon" variant="outline" onClick={() => updateQuantity(item.productId, item.quantity - 1)}><Minus className="h-3.5 w-3.5" /></Button><span className="w-8 text-center text-sm font-semibold">{item.quantity}</span><Button size="icon" variant="outline" onClick={() => updateQuantity(item.productId, item.quantity + 1)}><Plus className="h-3.5 w-3.5" /></Button><Button size="sm" variant="ghost" className="ml-2 text-destructive" onClick={() => updateQuantity(item.productId, 0)}><Trash2 className="h-3.5 w-3.5" />Retirer</Button></div></div><p className="font-semibold">{(item.quantity * item.unitPrice).toFixed(3)} DT</p></div>)}</div></section>}<aside className="h-fit rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-semibold">Résumé de la commande</h2><div className="mt-5 flex justify-between text-sm text-muted-foreground"><span>Sous-total</span><span>{totalPrice.toFixed(3)} DT</span></div><div className="my-4 border-t" /><div className="flex justify-between text-lg font-semibold"><span>Total</span><span>{totalPrice.toFixed(3)} DT</span></div><Link to="/client/checkout" className="mt-5 block"><Button className="w-full" disabled={!entries.length}>Passer au paiement<ArrowRight className="h-4 w-4" /></Button></Link></aside></div></div>;
}

export function ClientCheckoutPage() {
  const navigate = useNavigate(); const [note, setNote] = useState(''); const { cart, totalPrice, clearCart } = useCart(); const entries = Object.values(cart);
  const mutation = useMutation({ mutationFn: () => api<{ id: string }>('/client/orders', { method: 'POST', body: JSON.stringify({ note, items: entries.map((item) => ({ productId: item.productId, quantity: item.quantity })) }) }), onSuccess: (order) => { clearCart(); toast.success('Commande confirmée'); navigate(`/client/orders/${order.id}`); }, onError: (error: Error) => toast.error(error.message) });
  function submit(event: FormEvent) { event.preventDefault(); if (entries.length) mutation.mutate(); }
  return <div className="space-y-6"><PageHeader title="Finaliser la commande" subtitle="Vérifiez les informations avant confirmation." /><form onSubmit={submit} className="grid gap-6 lg:grid-cols-[1fr_380px]"><div className="space-y-5"><section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-4 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary">1</span><div><h2 className="font-semibold">Informations client</h2><p className="text-sm text-muted-foreground">Votre compte sera utilisé pour cette commande.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Nom</Label><Input className="mt-1" value={getCurrentUser()?.name ?? ''} readOnly /></div><div><Label>Email</Label><Input className="mt-1" value={getCurrentUser()?.username ?? ''} readOnly /></div></div></section><section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-4 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary">2</span><div><h2 className="font-semibold">Note de commande</h2><p className="text-sm text-muted-foreground">Une précision pour préparer votre commande.</p></div></div><Input value={note} onChange={(event) => setNote(event.target.value)} placeholder="Ex. livraison ou condition particulière (facultatif)" /></section></div><aside className="h-fit rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-semibold">Résumé</h2><div className="mt-4 space-y-3">{entries.map((item) => <div key={item.productId} className="flex justify-between gap-3 text-sm"><span>{item.productName} × {item.quantity}</span><span className="font-medium">{(item.unitPrice * item.quantity).toFixed(3)} DT</span></div>)}</div><div className="my-5 border-t" /><div className="flex justify-between text-lg font-semibold"><span>Total</span><span>{totalPrice.toFixed(3)} DT</span></div><Button className="mt-5 w-full" type="submit" disabled={!entries.length || mutation.isPending}>{mutation.isPending ? 'Confirmation…' : 'Confirmer la commande'}</Button><Link to="/client/cart" className="mt-3 block text-center text-sm font-medium text-muted-foreground">Modifier le panier</Link></aside></form></div>;
}

export function ClientOrdersPage() {
  const [status, setStatus] = useState(''); const { data = [], isLoading } = useQuery({ queryKey: ['client-orders', status], queryFn: () => api<Order[]>(`/client/orders${status ? `?status=${status}` : ''}`) });
  return <div className="space-y-6"><PageHeader title="Mes commandes" subtitle="Suivez vos achats et leur progression." actions={<Link to="/client/products"><Button><ShoppingBag className="h-4 w-4" />Nouvelle commande</Button></Link>} /><div className="flex gap-2 overflow-x-auto">{[['', 'Toutes'], ['PENDING', 'En attente'], ['ACCEPTED', 'Acceptées'], ['COMPLETED', 'Terminées']].map(([value, label]) => <Button key={value} size="sm" variant={status === value ? 'default' : 'outline'} onClick={() => setStatus(value)}>{label}</Button>)}</div><section className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="hidden grid-cols-[1.5fr_1fr_1fr_1fr_auto] gap-4 border-b bg-muted/30 px-5 py-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground md:grid"><span>Commande</span><span>Date</span><span>Articles</span><span>Total</span><span>Statut</span></div>{isLoading ? <TableSkeleton/> : !data.length ? <EmptyState icon={ShoppingBag} title="Aucune commande" text="Les commandes correspondant à ce filtre apparaîtront ici." /> : data.map((order) => <Link key={order.id} to={`/client/orders/${order.id}`} className="grid gap-2 border-b px-5 py-4 transition-colors last:border-0 hover:bg-muted/30 md:grid-cols-[1.5fr_1fr_1fr_1fr_auto] md:items-center md:gap-4"><div><p className="font-semibold">#{order.id.slice(0, 8)}</p><p className="text-xs text-muted-foreground md:hidden">{new Date(order.createdAt).toLocaleDateString('fr-FR')}</p></div><span className="hidden text-sm text-muted-foreground md:block">{new Date(order.createdAt).toLocaleDateString('fr-FR')}</span><span className="text-sm text-muted-foreground">{order.items?.length ?? 0} article(s)</span><span className="font-semibold">{Number(order.totalAmount).toFixed(3)} DT</span><Badge variant={statusVariant(order.status)}>{statusLabel(order.status)}</Badge></Link>)}</section></div>;
}

export function ClientOrderDetailPage() {
  const { id } = useParams(); const { data, isLoading } = useQuery({ queryKey: ['client-order', id], queryFn: () => api<{ id: string; status: string; totalAmount: number; note: string | null; createdAt: string; items: { product: { name: string }; quantity: number; unitPrice: number; totalPrice: number }[] }>(`/client/orders/${id}`) });
  if (isLoading || !data) return <OrderDetailSkeleton />;
  const timeline = ['PENDING', 'ACCEPTED', 'PREPARING', 'READY', 'COMPLETED']; const currentIndex = timeline.indexOf(data.status);
  return <div className="space-y-6"><PageHeader title={`Commande #${data.id.slice(0, 8)}`} subtitle={`Créée le ${new Date(data.createdAt).toLocaleString('fr-FR')}`} actions={<Badge variant={statusVariant(data.status)}>{statusLabel(data.status)}</Badge>} /><section className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-semibold">Progression</h2><div className="mt-6 grid grid-cols-5 gap-2">{timeline.map((step, index) => <div key={step} className="text-center"><div className={cn('mx-auto flex h-9 w-9 items-center justify-center rounded-full text-xs font-bold', index <= currentIndex && currentIndex >= 0 ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground')}>{index <= currentIndex && currentIndex >= 0 ? <CheckCircle2 className="h-4 w-4" /> : index + 1}</div><p className="mt-2 text-[11px] font-medium text-muted-foreground">{statusLabel(step)}</p></div>)}</div></section><div className="grid gap-6 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="mb-3 font-semibold">Articles commandés</h2><div className="divide-y divide-border/70">{data.items.map((item) => <div key={item.product.name} className="flex justify-between gap-4 py-3"><div><p className="font-medium">{item.product.name}</p><p className="text-sm text-muted-foreground">{Number(item.unitPrice).toFixed(3)} DT × {Number(item.quantity)}</p></div><p className="font-semibold">{Number(item.totalPrice).toFixed(3)} DT</p></div>)}</div></section><aside className="h-fit rounded-2xl border bg-card p-5 shadow-sm"><p className="text-sm text-muted-foreground">Total de la commande</p><p className="mt-1 text-2xl font-semibold">{Number(data.totalAmount).toFixed(3)} DT</p>{data.note ? <div className="mt-5 border-t pt-4"><p className="text-xs font-semibold uppercase text-muted-foreground">Votre note</p><p className="mt-1 text-sm">{data.note}</p></div> : null}</aside></div></div>;
}

export function ClientProfilePage() {
  const user = getCurrentUser();
  return <div className="space-y-6"><PageHeader title="Mon profil" subtitle="Les informations de votre compte CaféStock." /><section className="max-w-2xl rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center gap-4 border-b pb-5"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-primary/10 text-primary"><UserRound className="h-6 w-6" /></div><div><h2 className="font-semibold">{user?.name ?? 'Client'}</h2><p className="text-sm text-muted-foreground">Compte client</p></div></div><div className="grid gap-5 pt-5 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Email</p><p className="mt-1 font-medium">{user?.username ?? '—'}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Accès</p><p className="mt-1 font-medium">Portail client</p></div></div></section></div>;
}

function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Package }) { return <Card><CardContent className="flex items-center gap-4 p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><div><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>; }
function OrderRow({ order }: { order: Order }) { return <Link to={`/client/orders/${order.id}`} className="flex items-center justify-between gap-3 py-3 transition-colors hover:bg-muted/30"><div><p className="text-sm font-semibold">#{order.id.slice(0, 8)}</p><p className="text-xs text-muted-foreground">{new Date(order.createdAt).toLocaleDateString('fr-FR')} · {order.items?.length ?? 0} article(s)</p></div><div className="flex items-center gap-3"><Badge variant={statusVariant(order.status)}>{statusLabel(order.status)}</Badge><ArrowRight className="h-4 w-4 text-muted-foreground" /></div></Link>; }
function EmptyState({ icon: Icon, title, text, action }: { icon: typeof Package; title: string; text: string; action?: React.ReactNode }) { return <div className="p-10 text-center"><Icon className="mx-auto mb-3 h-9 w-9 text-muted-foreground/40" /><p className="font-medium">{title}</p><p className="mt-1 text-sm text-muted-foreground">{text}</p>{action ? <div className="mt-4">{action}</div> : null}</div>; }
function LoadingCard() { return <div className="h-[390px] animate-pulse rounded-2xl border bg-muted/40" />; }
